[build]
  command = "python3 -m pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200

[dev]
  command = "streamlit run app.py --server.address=0.0.0.0 --server.port=8501"
  targetPort = 8501
  port = 8888
  publish = "."
  framework = "streamlit"